# Generated by Django 4.0.1 on 2022-01-31 12:08

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Parcipant name')),
                ('contact_no', phonenumber_field.modelfields.PhoneNumberField(help_text='For India start with +91 ', max_length=128, region=None, verbose_name='Contact No ')),
                ('email_id', models.EmailField(max_length=254, verbose_name='Enter your Email ID')),
                ('event_list', models.CharField(blank=True, choices=[('3limited_model', 'limited_model - 3'), ('4valkyrie-app', 'valkyrie-app - 4'), ('7Event 10', 'Event 10 - 7')], max_length=200, null=True)),
                ('registration_type', models.CharField(choices=[('Individual', 'Individual'), ('Group', 'Group')], max_length=200)),
                ('no_of_people', models.IntegerField(default=1, verbose_name='No. of people ')),
            ],
        ),
    ]
