# Generated by Django 4.0.1 on 2022-01-31 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Participant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantdata',
            name='event_list',
            field=models.CharField(blank=True, choices=[('3limited_model', 'limited_model - 3'), ('4valkyrie-app', 'valkyrie-app - 4'), ('7Event 10', 'Event 10 - 7'), ('9Event100', 'Event100 - 9'), ('11Event 4', 'Event 4 - 11'), ('12limited_model', 'limited_model - 12'), ('13limited_model', 'limited_model - 13'), ('14valkyrie-app', 'valkyrie-app - 14'), ('15valkyrie-app', 'valkyrie-app - 15')], max_length=200, null=True),
        ),
    ]
