# Generated by Django 4.0.1 on 2022-01-31 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Participant', '0005_alter_participantdata_event_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantdata',
            name='event_list',
            field=models.CharField(blank=True, choices=[('18Admin Event 1', 'Admin Event 1 - 18'), ('19Admin Event 2', 'Admin Event 2 - 19'), ('23Form Event 1', 'Form Event 1 - 23'), ('24Form Event 1', 'Form Event 1 - 24')], max_length=200, null=True),
        ),
    ]
