# Generated by Django 4.0.1 on 2022-01-28 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eventdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Event name')),
                ('description', models.TextField(blank=True, default='This is Description box.', verbose_name="Event's description")),
                ('link', models.URLField(blank=True, max_length=10000, verbose_name='Link of the poster')),
                ('From', models.DateTimeField(help_text='Note : time in UTC', null=True, verbose_name='From')),
                ('To', models.DateTimeField(help_text='Note : time in UTC', null=True, verbose_name='To')),
                ('reg_deadline', models.DateTimeField(help_text='Note : time in UTC', null=True, verbose_name='Registration Deadline')),
                ('host_email', models.EmailField(default='your email address', max_length=254, verbose_name="Host's Email ID")),
                ('host_password', models.CharField(max_length=33, verbose_name='Password for event')),
            ],
        ),
    ]
