# Generated by Django 4.0.1 on 2022-01-31 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdata',
            name='From',
            field=models.DateTimeField(null=True, verbose_name='From'),
        ),
        migrations.AlterField(
            model_name='eventdata',
            name='To',
            field=models.DateTimeField(null=True, verbose_name='To'),
        ),
        migrations.AlterField(
            model_name='eventdata',
            name='host_email',
            field=models.EmailField(max_length=254, verbose_name="Host's Email ID"),
        ),
        migrations.AlterField(
            model_name='eventdata',
            name='reg_deadline',
            field=models.DateTimeField(null=True, verbose_name='Registration Deadline'),
        ),
    ]
