# Generated by Django 4.0.1 on 2022-01-31 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0002_alter_eventdata_from_alter_eventdata_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdata',
            name='description',
            field=models.TextField(blank=True, verbose_name="Event's description"),
        ),
    ]
