# Generated by Django 4.0.1 on 2022-01-28 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Participant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantdata',
            name='event_list',
            field=models.CharField(blank=True, choices=[('1Sample Event1', 'Sample Event1 - 1'), ('2romantic', 'romantic - 2')], max_length=200),
        ),
    ]
